apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"elasticsearch-pvc","namespace":"elk"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"manual"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2026-06-04T07:54:26Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: elasticsearch-pvc
  namespace: elk
  resourceVersion: "40997"
  uid: c1aa0112-71f0-46ce-a1f5-86c66d8df87c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: es-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
