apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"es-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/data/elasticsearch"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"manual"}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2026-06-04T07:55:33Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: es-pv
  resourceVersion: "40995"
  uid: 81d63e71-ecdb-4bfc-8f4d-0a92061157d5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: elasticsearch-pvc
    namespace: elk
    resourceVersion: "40850"
    uid: c1aa0112-71f0-46ce-a1f5-86c66d8df87c
  hostPath:
    path: /data/elasticsearch
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2026-06-04T07:55:46Z"
  phase: Bound
